name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.11.0

      - name: Install dependencies
        run: |
          opam install dune ocamlgraph
             
      - name: Install cil
        run: opam pin add git+https://github.com/prosyslab/cil.git

      - run: |
            eval $(opam env)
            make test
